// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTIvxPn04C_6fDkz80226hBsYYDs_5ek',
    appId: '1:330746510559:web:47af19d74ec88d5d403d6a',
    messagingSenderId: '330746510559',
    projectId: 'reddit-clone-d60e0',
    authDomain: 'reddit-clone-d60e0.firebaseapp.com',
    storageBucket: 'reddit-clone-d60e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD751tU8XIn9ScfE56JMvByBUiefQbpzZo',
    appId: '1:330746510559:android:1b258e225d13672a403d6a',
    messagingSenderId: '330746510559',
    projectId: 'reddit-clone-d60e0',
    storageBucket: 'reddit-clone-d60e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC76vdR3xoKP5YNFYLBolxzrz1QKOvW-q8',
    appId: '1:330746510559:ios:6652d7ced3ecf110403d6a',
    messagingSenderId: '330746510559',
    projectId: 'reddit-clone-d60e0',
    storageBucket: 'reddit-clone-d60e0.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
